let combos = {
  dwarf: ["deathKnight", "hunter", "mage", "monk", "paladin", "priest", "rogue", "shaman", "warlock", "warrior"],
  gnome: ["deathKnight", "hunter", "mage", "monk", "priest", "rogue", "warlock", "warrior"],
  human: ["deathKnight", "hunter", "mage", "monk", "paladin", "priest", "rogue", "warlock", "warrior"],
  nightElf: ["deathKnight", "demonHunter", "druid", "hunter", "mage", "monk", "priest", "rogue", "warlock", "warrior"],
  draenei: ["deathKnight", "hunter", "mage", "monk", "paladin", "priest", "rogue", "shaman", "warlock", "warrior"],
  worgen: ["deathKnight", "druid", "hunter", "mage", "monk", "priest", "rogue", "warlock", "warrior"],
  darkIron: ["deathKnight", "hunter", "mage", "monk", "paladin", "priest", "rogue", "shaman", "warlock", "warrior"],
  kulTiran: ["deathKnight", "druid", "hunter", "mage", "monk", "priest", "rogue", "shaman", "warlock", "warrior"],
  lightforged: ["deathKnight", "hunter", "mage", "monk", "paladin", "priest", "rogue", "warlock", "warrior"],
  mechagnome: ["deathKnight", "hunter", "mage", "monk", "priest", "rogue", "warlock", "warrior"],
  voidElf: ["deathKnight", "hunter", "mage", "monk", "priest", "rogue", "warlock", "warrior"],

  pandaren: ["deathKnight", "hunter", "mage", "monk", "priest", "rogue", "shaman", "warlock", "warrior"],
  dracthyr: ["evoker"],
  earthen: ["deathKnight", "hunter", "mage", "monk", "paladin", "priest", "rogue", "shaman", "warlock", "warrior"],

  orc: ["deathKnight", "hunter", "mage", "monk", "priest", "rogue", "shaman", "warlock", "warrior"],
  tauren: ["deathKnight", "druid", "hunter", "mage", "monk", "paladin", "priest", "rogue", "shaman", "warlock", "warrior"],
  troll: ["deathKnight", "druid", "hunter", "mage", "monk", "priest", "rogue", "shaman", "warlock", "warrior"],
  undead: ["deathKnight", "hunter", "mage", "monk", "priest", "rogue", "warlock", "warrior"],
  bloodElf: ["deathKnight", "demonHunter", "hunter", "mage", "monk", "paladin", "priest", "rogue", "warlock", "warrior"],
  goblin: ["deathKnight", "hunter", "mage", "monk", "priest", "rogue", "shaman", "warlock", "warrior"],
  highmountain: ["deathKnight", "druid", "hunter", "mage", "monk", "priest", "rogue", "shaman", "warlock", "warrior"],
  magHar: ["deathKnight", "hunter", "mage", "monk", "priest", "rogue", "shaman", "warlock", "warrior"],
  nightborne: ["deathKnight", "hunter", "mage", "monk", "priest", "rogue", "warlock", "warrior"],
  vulpera: ["deathKnight", "hunter", "mage", "monk", "priest", "rogue", "shaman", "warlock", "warrior"],
  zandalari: ["deathKnight", "druid", "hunter", "mage", "monk", "paladin", "priest", "rogue", "shaman", "warlock", "warrior"],
};
